#!/usr/bin/env bash
KLASSE="&0"

POSITIONAL_ARGS=()
OUT_COMMAND="notify-send"

while [[ $# -gt 0 ]]; do
    case $1 in
	-d|--date)
	    DATE="$2"
	    shift
	    shift
	    ;;
	-stdout)
	    OUT_COMMAND="echo"
	    shift
	    ;;
    esac
done

if [[ "$(nmcli networking connectivity check)" == "none" ]]; then
    $OUT_COMMAND "No internet"
    exit 1
fi


curl -u "&1" --basic -l "https://geschuetzt.bszet.de/s-lk-vw/Vertretungsplaene/vertretungsplan-bgy.pdf" > /tmp/vertretungsplan;

# Suche alle zeilen, welche entweder ein Datum oder vertretung für die klasse sind
datum_und_vertretung=$(pdftotext -layout -nopgbrk /tmp/vertretungsplan - | grep -E "($klasse)|([0-9]{1,2}\.[0-9]{1,2}\.[0-9]{4})")

# Ich bin mir nicht sicher ob das Datum mit nullen (zero padded) oder ohne ist. Dieses regex prüft für beides 
regex=$(echo "($(date -d 'tomorrow' +'%d.%m.%Y'))|($(date -d 'tomorrow' +'%_d.%_m.%Y'))" | tr -d " ")

# Entfernt alle Zeilen in der vergangenheit und unnötige leerzeichen
truncated=$(echo "$datum_und_vertretung" | sed -E "0,/$regex/d" | tr -s " ")

if [ -z "$truncated" ]; then
    $OUT_COMMAND "Keine Vertretung :c"
else
    $OUT_COMMAND "$truncated"
fi
